# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib civ6saves
#' @export
readMap <- function(path) {
    invisible(.Call('_civ6saves_readMap', PACKAGE = 'civ6saves', path))
}

